In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import requests
from bs4 import BeautifulSoup
import warnings
warnings.filterwarnings("ignore")

In [9]:
url="https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off"

In [11]:
response=requests.get(url)
response

In [13]:
headers={"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36"}

In [15]:
response=requests.get(url,headers=headers)
response

In [17]:
pagecontent=response.text

In [19]:
soup=BeautifulSoup(pagecontent)

In [21]:
pname=soup.find("div",attrs={"class":"RG5Slk"})
pname

In [23]:
productname = []
for x in soup.find_all('div',attrs={'class':'RG5Slk'}):
    productname.append(x.text if x else np.nan)
#display all product name
for name in productname:
    print(name)

MOTOROLA edge 70 pro (Satin-Luxe PANTONE Tea (Green), 256 GB)
MOTOROLA edge 70 pro (Satin-Luxe PANTONE Tea (Green), 256 GB)
realme P4 Lite 5G (Mosaic Green, 64 GB)
Ai+ Pulse 1 (Sparkle Red, 64 GB)
MOTOROLA edge 70 pro (Tailored Fabric - PANTONE Titan (Blue), 256 GB)
MOTOROLA edge 70 pro (Marble - PANTONE Lily white (white), 256 GB)
Jmax MINI
Nokia 105 Classic Single Sim Keypad Phone, Without Charger
MOTOROLA g35 5G (Leaf Green, 128 GB)
POCO C75 5G (Enchanted Green, 128 GB)
MOTOROLA edge 70 pro (Tailored Fabric - PANTONE Titan (Blue), 256 GB)
MOTOROLA edge 70 pro (Marble - PANTONE Lily white (white), 256 GB)
Jio Bharat V4 JBV191M2 4G UPI Phone
MOTOROLA g67 power 5G (Pantone Parachute, 128 GB)
POCO C85x (Sunset Gold, 64 GB)
Ai+ Pulse 1 (Blue, 64 GB)
MOTOROLA Edge 70 Fusion (Pantone BLUE SURF, 128 GB)
realme P4x 5G (Matte Silver, 256 GB)
Ai+ Pulse 2 (Blue, 64 GB)
realme P4 Lite 5G (Mosaic Green, 128 GB)
Nokia All-New 105 Single Sim Keypad Phone with Built-in UPI Payments
realme P4 Lite (Beach Gold, 128 GB)
POCO C75 5G (Aqua Bliss, 64 GB)
REDMI A5 (Pondicherry Blue, 64 GB)

In [25]:
rating = soup.find("div",attrs={"class":"MKiFS6"})
rating

<div class="MKiFS6">4.4<img class="PZfbSE" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMyIgaGVpZ2h0PSIxMiI+PHBhdGggZmlsbD0iI0ZGRiIgZD0iTTYuNSA5LjQzOWwtMy42NzQgMi4yMy45NC00LjI2LTMuMjEtMi44ODMgNC4yNTQtLjQwNEw2LjUuMTEybDEuNjkgNC4wMSA0LjI1NC40MDQtMy4yMSAyLjg4Mi45NCA0LjI2eiIvPjwvc3ZnPg=="/></div>

In [27]:
ratings = []
for x in soup.find_all('div',attrs={'class':'MKiFS6'}):
    ratings.append(x.text if x else np.nan)
#display all ratings
for name in ratings:
    print(name)

4.4
4.3
3.8
4
4.2
4.2
3.8
4.4
4.2
4.3
4.4
4.4
4.6
4.4
3.7
4.4
4.2
4.1
4
5
1
3.8
4
1
4.6
4
5
4.4
5
2
4.3
5
4

In [29]:
disc_price=soup.find("div",attrs={"class":"hZ3P6w DeU9vF"})
disc_price

In [52]:
price = []
for x in soup.find_all('div',attrs={'class':'hZ3P6w DeU9vF'}):
    price.append(x.text if x else np.nan)
#display all ratings
for name in price:
    print(name)

₹12,999
₹7,999
₹777
₹1,034
₹12,499
₹799
₹11,499
₹16,999
₹11,499
₹20,999
₹15,999
₹7,999
₹8,999
₹13,999
₹1,349
₹8,999
₹10,999
₹10,999
₹33,999
₹29,999
₹11,499
₹15,999
₹8,999
₹8,999

In [60]:
reviews=soup.find("span",attrs={"class":"PvbNMB"})
reviews

In [66]:
for i in range(1,100):
    print(f"https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page={i}")

https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=3
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=4
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=5
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=6
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=7
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=8
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=9
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=10
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=11
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=12
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=13
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=14
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=15
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=16
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=17
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=18
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=19
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=20
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=21
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=22
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=23
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=24
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=25
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=26
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=27
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=28
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=29
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=30
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=31
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=32
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=33
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=34
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=35
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=36
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=37
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=38
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=39
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=40
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=41
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=42
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=43
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=44
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=45
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=46
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=47
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=48
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=49
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=50
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=51
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=52
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=53
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=54
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=55
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=56
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=57
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=58
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=59
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=60
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=61
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=62
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=63
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=64
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=65
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=66
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=67
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=68
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=69
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=70
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=71
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=72
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=73
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=74
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=75
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=76
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=77
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=78
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=79
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=80
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=81
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=82
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=83
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=84
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=85
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=86
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=87
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=88
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=89
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=90
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=91
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=92
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=93
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=94
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=95
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=96
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=97
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=98
https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=99

In [51]:
from bs4 import BeautifulSoup
import requests
import numpy as np
import time

productname = [] 
price = []
rating = []
features = []
pagenum = []
original_price = []
Discount = []
Review = []

total_time=time.time()

for i in range(1,100):
    start_time=time.time()
    URL= f"https://www.flipkart.com/search?q=phones&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page={i}"

    page=requests.get(URL,headers=headers)
    soup=BeautifulSoup(page.text,"html.parser")
    
    for x in soup.find_all('div', attrs={'class':'ZFwe0M row'}):
        pname = x.find('div', attrs={'class':'RG5Slk'})
        cost = x.find('div', attrs={'class':'hZ3P6w DeU9vF'})
        rat = x.find('div', attrs={'class':'MKiFS6'})
        specs = x.find('div', attrs={'class':'CMXw7N'})
        op = x.find('div', attrs={'class':'kRYCnD gxR4EY'})
        discount = x.find('div', attrs={'class':'HQe8jr'})
        reviews = x.find('span', attrs={'class':'PvbNMB'})
        
        productname.append(pname.text if pname else np.nan)
        price.append(cost.text if cost else np.nan)
        rating.append(rat.text if rat else np.nan)
        features.append(specs.text if specs else np.nan)
        original_price.append(op.text if op else np.nan)
        Discount.append(discount.text if discount else np.nan)
        Review.append(reviews.text if reviews else np.nan)
        
        pagenum.append(i)

    print(f'Page {i} completed in {time.time()-start_time:.2f} seconds')

print("Total Time Completed in seconds", str(time.time()-total_time))

Page 1 completed in 1.77 seconds
Page 2 completed in 0.61 seconds
Page 3 completed in 0.50 seconds
Page 4 completed in 0.62 seconds
Page 5 completed in 0.49 seconds
Page 6 completed in 0.63 seconds
Page 7 completed in 0.65 seconds
Page 8 completed in 0.54 seconds
Page 9 completed in 0.61 seconds
Page 10 completed in 0.63 seconds
Page 11 completed in 0.60 seconds
Page 12 completed in 0.52 seconds
Page 13 completed in 0.67 seconds
Page 14 completed in 0.56 seconds
Page 15 completed in 0.51 seconds
Page 16 completed in 0.49 seconds
Page 17 completed in 1.77 seconds
Page 18 completed in 0.63 seconds
Page 19 completed in 0.63 seconds
Page 20 completed in 0.62 seconds
Page 21 completed in 0.59 seconds
Page 22 completed in 0.48 seconds
Page 23 completed in 0.51 seconds
Page 24 completed in 0.50 seconds
Page 25 completed in 0.71 seconds
Page 26 completed in 0.58 seconds
Page 27 completed in 0.66 seconds
Page 28 completed in 0.53 seconds
Page 29 completed in 0.53 seconds
Page 30 completed in 0.52 seconds
Page 31 completed in 0.70 seconds
Page 32 completed in 0.62 seconds
Page 33 completed in 0.57 seconds
Page 34 completed in 0.63 seconds
Page 35 completed in 0.52 seconds
Page 36 completed in 0.56 seconds
Page 37 completed in 0.87 seconds
Page 38 completed in 0.78 seconds
Page 39 completed in 0.48 seconds
Page 40 completed in 0.50 seconds
Page 41 completed in 0.53 seconds
Page 42 completed in 1.35 seconds
Page 43 completed in 0.22 seconds
Page 44 completed in 0.21 seconds
Page 45 completed in 0.27 seconds
Page 46 completed in 0.23 seconds
Page 47 completed in 0.36 seconds
Page 48 completed in 0.23 seconds
Page 49 completed in 0.24 seconds
Page 50 completed in 0.29 seconds
Page 51 completed in 0.38 seconds
Page 52 completed in 0.22 seconds
Page 53 completed in 0.19 seconds
Page 54 completed in 0.36 seconds
Page 55 completed in 0.24 seconds
Page 56 completed in 0.29 seconds
Page 57 completed in 0.37 seconds
Page 58 completed in 0.34 seconds
Page 59 completed in 0.33 seconds
Page 60 completed in 0.41 seconds
Page 61 completed in 0.39 seconds
Page 62 completed in 0.43 seconds
Page 63 completed in 0.33 seconds
Page 64 completed in 0.28 seconds
Page 65 completed in 0.21 seconds
Page 66 completed in 0.23 seconds
Page 67 completed in 0.33 seconds
Page 68 completed in 0.30 seconds
Page 69 completed in 0.34 seconds
Page 70 completed in 0.33 seconds
Page 71 completed in 0.34 seconds
Page 72 completed in 0.59 seconds
Page 73 completed in 0.34 seconds
Page 74 completed in 1.45 seconds
Page 75 completed in 0.22 seconds
Page 76 completed in 0.22 seconds
Page 77 completed in 0.33 seconds
Page 78 completed in 0.19 seconds
Page 79 completed in 0.48 seconds
Page 80 completed in 0.25 seconds
Page 81 completed in 0.34 seconds
Page 82 completed in 0.25 seconds
Page 83 completed in 0.20 seconds
Page 84 completed in 0.19 seconds
Page 85 completed in 0.29 seconds
Page 86 completed in 0.22 seconds
Page 87 completed in 0.26 seconds
Page 88 completed in 0.30 seconds
Page 89 completed in 0.31 seconds
Page 90 completed in 0.45 seconds
Page 91 completed in 0.41 seconds
Page 92 completed in 0.37 seconds
Page 93 completed in 0.28 seconds
Page 94 completed in 0.19 seconds
Page 95 completed in 0.19 seconds
Page 96 completed in 0.29 seconds
Page 97 completed in 0.29 seconds
Page 98 completed in 0.32 seconds
Page 99 completed in 0.37 seconds
Total Time Completed in seconds 46.09181809425354

In [53]:
df = pd.DataFrame({
    "Product Name": productname,
    "Price": price,
    "Original Price": original_price,
    "Discount": Discount,
    "Rating": rating,
    "Reviews": Review,
    "Features": features,
    "Page Number": pagenum
})

In [55]:
df

,Product Name,Price,Original Price,Discount,Rating,Reviews,Features,Page Number
0,MOTOROLA edge 70 pro (Satin-Luxe PANTONE Tea (...,"₹38,999","₹51,999",25% off,NaN,NaN,8 GB RAM | 256 GB ROM17.27 cm (6.8 inch) Full ...,1
1,MOTOROLA edge 70 pro (Marble - PANTONE Lily wh...,"₹41,999","₹56,999",26% off,NaN,NaN,12 GB RAM | 256 GB ROM17.27 cm (6.8 inch) Full...,1
2,"realme P4 Lite 5G (Mosaic Green, 64 GB)","₹12,999","₹19,999",35% off,4.4,"1,745 Ratings & 89 Reviews",4 GB RAM | 64 GB ROM17.27 cm (6.8 inches) HD+ ...,1
3,"Ai+ Pulse 1 (Sparkle Red, 64 GB)","₹7,999",NaN,NaN,4.3,"49,268 Ratings & 2,888 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB17....,1
4,MOTOROLA edge 70 pro (Satin-Luxe PANTONE Tea (...,"₹41,999","₹56,999",26% off,NaN,NaN,12 GB RAM | 256 GB ROM17.27 cm (6.8 inch) Full...,1
...,...,...,...,...,...,...,...,...
979,"OPPO Reno15 Pro Mini 5G (Glacier White, 512 GB)","₹64,999","₹69,999",7% off,4.6,585 Ratings & 94 Reviews,12 GB RAM | 512 GB ROM16.05 cm (6.32 inch) Ful...,41
980,"Nothing Phone (3a) Pro (Grey, 256 GB)","₹31,999","₹34,999",8% off,4.5,"15,174 Ratings & 1,101 Reviews",8 GB RAM | 256 GB ROM43.66 cm (17.19 cm) Full ...,41
981,"Tecno Spark 20 Pro 5G (Glossy White, 128 GB)","₹15,890","₹19,999",20% off,4.1,258 Ratings & 24 Reviews,8 GB RAM | 128 GB ROM | Expandable Upto 1 TB17...,41
982,"Nothing Phone (3a) Pro (Black, 128 GB)","₹29,999","₹32,999",9% off,4.5,"15,174 Ratings & 1,101 Reviews",8 GB RAM | 128 GB ROM43.66 cm (17.19 cm) Full ...,41
983,"Tecno Spark 20 Pro 5G (Neon Green, 128 GB)","₹15,880","₹21,999",27% off,4.1,258 Ratings & 24 Reviews,8 GB RAM | 128 GB ROM17.22 cm (6.78 inch) HD+ ...,41

In [61]:
df.to_csv("mobiles.csv",index=False)

In [65]:
df=pd.read_csv("mobiles.csv")
df

,Product Name,Price,Original Price,Discount,Rating,Reviews,Features,Page Number
0,MOTOROLA edge 70 pro (Satin-Luxe PANTONE Tea (...,"₹38,999","₹51,999",25% off,NaN,NaN,8 GB RAM | 256 GB ROM17.27 cm (6.8 inch) Full ...,1
1,MOTOROLA edge 70 pro (Marble - PANTONE Lily wh...,"₹41,999","₹56,999",26% off,NaN,NaN,12 GB RAM | 256 GB ROM17.27 cm (6.8 inch) Full...,1
2,"realme P4 Lite 5G (Mosaic Green, 64 GB)","₹12,999","₹19,999",35% off,4.4,"1,745 Ratings & 89 Reviews",4 GB RAM | 64 GB ROM17.27 cm (6.8 inches) HD+ ...,1
3,"Ai+ Pulse 1 (Sparkle Red, 64 GB)","₹7,999",NaN,NaN,4.3,"49,268 Ratings & 2,888 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1 TB17....,1
4,MOTOROLA edge 70 pro (Satin-Luxe PANTONE Tea (...,"₹41,999","₹56,999",26% off,NaN,NaN,12 GB RAM | 256 GB ROM17.27 cm (6.8 inch) Full...,1
...,...,...,...,...,...,...,...,...
979,"OPPO Reno15 Pro Mini 5G (Glacier White, 512 GB)","₹64,999","₹69,999",7% off,4.6,585 Ratings & 94 Reviews,12 GB RAM | 512 GB ROM16.05 cm (6.32 inch) Ful...,41
980,"Nothing Phone (3a) Pro (Grey, 256 GB)","₹31,999","₹34,999",8% off,4.5,"15,174 Ratings & 1,101 Reviews",8 GB RAM | 256 GB ROM43.66 cm (17.19 cm) Full ...,41
981,"Tecno Spark 20 Pro 5G (Glossy White, 128 GB)","₹15,890","₹19,999",20% off,4.1,258 Ratings & 24 Reviews,8 GB RAM | 128 GB ROM | Expandable Upto 1 TB17...,41
982,"Nothing Phone (3a) Pro (Black, 128 GB)","₹29,999","₹32,999",9% off,4.5,"15,174 Ratings & 1,101 Reviews",8 GB RAM | 128 GB ROM43.66 cm (17.19 cm) Full ...,41
983,"Tecno Spark 20 Pro 5G (Neon Green, 128 GB)","₹15,880","₹21,999",27% off,4.1,258 Ratings & 24 Reviews,8 GB RAM | 128 GB ROM17.22 cm (6.78 inch) HD+ ...,41